# Generated by Django 5.0.6 on 2024-09-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrenadores',
            fields=[
                ('id_entrenador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_entrenador', models.CharField(max_length=100)),
                ('apellido_entrenador', models.CharField(max_length=100)),
                ('dni_entrenador', models.CharField(max_length=20, unique=True)),
                ('fecha_nac_entrenador', models.DateField()),
                ('foto_entrenador', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrenadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('logo_equipo', models.TextField(blank=True, null=True)),
                ('foto_equipo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquiposXEntrenadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipos_x_entrenadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fechas',
            fields=[
                ('id_fecha', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fecha', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fechas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Figuras',
            fields=[
                ('id_figura', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'figuras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id_jugador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_jugador', models.CharField(max_length=100)),
                ('apellido_jugador', models.CharField(max_length=100)),
                ('dni_jugador', models.CharField(max_length=20, unique=True)),
                ('fecha_nac_jugador', models.DateField()),
                ('foto_jugador', models.TextField(blank=True, null=True)),
                ('activo_jugador', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jugadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_partido', models.DateField(blank=True, null=True)),
                ('hora_partido', models.TimeField(blank=True, null=True)),
                ('destacado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planillas',
            fields=[
                ('id_planilla', models.AutoField(primary_key=True, serialize=False)),
                ('goles', models.IntegerField(blank=True, null=True)),
                ('num_camiseta', models.IntegerField(blank=True, null=True)),
                ('participo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planillas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Predios',
            fields=[
                ('id_predio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_predio', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'predios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PremiosEquipos',
            fields=[
                ('id_premio_equipo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'premios_equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PremiosGrupales',
            fields=[
                ('id_premio_grupal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_premio_grupal', models.CharField(max_length=100)),
                ('foto_premio_grupal', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'premios_grupales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PremiosIndividuales',
            fields=[
                ('id_premio_individual', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_premio_individual', models.CharField(max_length=100)),
                ('foto_premio_individual', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'premios_individuales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PremiosJugadores',
            fields=[
                ('id_premio_jugador', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'premios_jugadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('goles_equipo_1', models.IntegerField(blank=True, null=True)),
                ('goles_equipo_2', models.IntegerField(blank=True, null=True)),
                ('penales', models.IntegerField(blank=True, null=True)),
                ('penales_equipo_1', models.IntegerField(blank=True, null=True)),
                ('penales_equipo_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resultados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaDePosiciones',
            fields=[
                ('id_tabla', models.AutoField(primary_key=True, serialize=False)),
                ('puntos', models.IntegerField(blank=True, null=True)),
                ('partidos_jugados', models.IntegerField(blank=True, null=True)),
                ('partidos_ganados', models.IntegerField(blank=True, null=True)),
                ('partidos_empatados', models.IntegerField(blank=True, null=True)),
                ('partidos_perdidos', models.IntegerField(blank=True, null=True)),
                ('goles_a_favor', models.IntegerField(blank=True, null=True)),
                ('goles_en_contra', models.IntegerField(blank=True, null=True)),
                ('diferencia_goles', models.IntegerField(blank=True, null=True)),
                ('tarjetas_amarillas', models.IntegerField(blank=True, null=True)),
                ('tarjetas_rojas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_de_posiciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_tarjeta', models.CharField(blank=True, max_length=8, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarjetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temporadas',
            fields=[
                ('id_temporada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_temporada', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temporadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemporadasXTorneosXEquiposXJugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'temporadas_x_torneos_x_equipos_x_jugadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTorneos',
            fields=[
                ('id_tipo_torneo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_torneo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_torneos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Torneos',
            fields=[
                ('id_torneo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_torneo', models.CharField(max_length=100)),
                ('año', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'torneos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Traspasos',
            fields=[
                ('id_traspaso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_transferencia', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'traspasos',
                'managed': False,
            },
        ),
    ]
