# Generated by Django 5.1.1 on 2024-09-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjetas',
            options={'managed': True},
        ),
    ]
