# Generated by Django 5.1.1 on 2024-10-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entrenador', models.CharField(max_length=100)),
                ('apellido_entrenador', models.CharField(max_length=100)),
                ('dni_entrenador', models.CharField(max_length=20, unique=True)),
                ('fecha_nac_entrenador', models.DateField()),
                ('foto_entrenador', models.ImageField(blank=True, null=True, upload_to='fotos_jugador/')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('logo_equipo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('foto_equipo', models.ImageField(blank=True, null=True, upload_to='fotos_equipo/')),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fecha', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fechas',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador', models.CharField(max_length=100)),
                ('apellido_jugador', models.CharField(max_length=100)),
                ('dni_jugador', models.CharField(max_length=20, unique=True)),
                ('fecha_nac_jugador', models.DateField()),
                ('foto_jugador', models.ImageField(blank=True, null=True, upload_to='fotos_jugador/')),
                ('activo_jugador', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_predio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PremiosGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_premio_grupal', models.CharField(max_length=100)),
                ('foto_premio_grupal', models.ImageField(blank=True, null=True, upload_to='premio_grupal/')),
            ],
        ),
        migrations.CreateModel(
            name='PremiosIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_premio_individual', models.CharField(max_length=100)),
                ('foto_premio_individual', models.ImageField(blank=True, null=True, upload_to='premio_individual/')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_temporada', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temporadas',
            },
        ),
        migrations.CreateModel(
            name='TipoTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_torneo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoXEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('id_entrenador', models.ForeignKey(blank=True, db_column='id_entrenador', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.entrenador')),
                ('id_equipo', models.ForeignKey(blank=True, db_column='id_equipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.equipo')),
            ],
            options={
                'db_table': 'equipos_x_entrenadores',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_partido', models.DateField(blank=True, null=True)),
                ('hora_partido', models.TimeField(blank=True, null=True)),
                ('destacado', models.BooleanField(blank=True, default=False)),
                ('id_equipo_1', models.ForeignKey(blank=True, db_column='id_equipo_1', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.equipo')),
                ('id_equipo_2', models.ForeignKey(blank=True, db_column='id_equipo_2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_id_equipo_2_set', to='myapp.equipo')),
                ('id_fecha', models.ForeignKey(blank=True, db_column='id_fecha', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.fecha')),
                ('id_grupo', models.ForeignKey(blank=True, db_column='id_grupo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.grupo')),
                ('id_predio', models.ForeignKey(blank=True, db_column='id_predio', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.predio')),
                ('id_temporada', models.ForeignKey(blank=True, db_column='id_temporada', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.temporada')),
            ],
            options={
                'db_table': 'partidos',
            },
        ),
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jugador', models.ForeignKey(blank=True, db_column='id_jugador', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.jugador')),
                ('id_partido', models.ForeignKey(blank=True, db_column='id_partido', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.partido')),
            ],
            options={
                'db_table': 'figuras',
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.IntegerField(blank=True, null=True)),
                ('num_camiseta', models.IntegerField(blank=True, null=True)),
                ('participo', models.BooleanField(blank=True, default=False)),
                ('id_equipo', models.ForeignKey(blank=True, db_column='id_equipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.equipo')),
                ('id_jugador', models.ForeignKey(blank=True, db_column='id_jugador', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.jugador')),
                ('id_partido', models.ForeignKey(blank=True, db_column='id_partido', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.partido')),
            ],
            options={
                'db_table': 'planillas',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_equipo_1', models.IntegerField(blank=True, null=True)),
                ('goles_equipo_2', models.IntegerField(blank=True, null=True)),
                ('penales', models.BooleanField(blank=True, default=False)),
                ('penales_equipo_1', models.IntegerField(blank=True, null=True)),
                ('penales_equipo_2', models.IntegerField(blank=True, null=True)),
                ('id_partido', models.ForeignKey(blank=True, db_column='id_partido', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.partido')),
            ],
            options={
                'db_table': 'resultados',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarjeta', models.CharField(max_length=8)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_jugador', models.ForeignKey(db_column='id_jugador', on_delete=django.db.models.deletion.CASCADE, to='myapp.jugador')),
                ('id_partido', models.ForeignKey(db_column='id_partido', on_delete=django.db.models.deletion.CASCADE, to='myapp.partido')),
            ],
            options={
                'db_table': 'tarjetas',
            },
        ),
        migrations.CreateModel(
            name='TablaDePosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(blank=True, null=True)),
                ('partidos_jugados', models.IntegerField(blank=True, null=True)),
                ('partidos_ganados', models.IntegerField(blank=True, null=True)),
                ('partidos_empatados', models.IntegerField(blank=True, null=True)),
                ('partidos_perdidos', models.IntegerField(blank=True, null=True)),
                ('goles_a_favor', models.IntegerField(blank=True, null=True)),
                ('goles_en_contra', models.IntegerField(blank=True, null=True)),
                ('diferencia_goles', models.IntegerField(blank=True, null=True)),
                ('tarjetas_amarillas', models.IntegerField(blank=True, null=True)),
                ('tarjetas_rojas', models.IntegerField(blank=True, null=True)),
                ('id_equipo', models.ForeignKey(blank=True, db_column='id_equipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.equipo')),
                ('id_grupo', models.ForeignKey(blank=True, db_column='id_grupo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.grupo')),
                ('id_temporada', models.ForeignKey(blank=True, db_column='id_temporada', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.temporada')),
            ],
            options={
                'db_table': 'tabla_de_posiciones',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='id_temporada',
            field=models.ForeignKey(blank=True, db_column='id_temporada', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.temporada'),
        ),
        migrations.AddField(
            model_name='fecha',
            name='id_temporada',
            field=models.ForeignKey(blank=True, db_column='id_temporada', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.temporada'),
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_torneo', models.CharField(max_length=100)),
                ('año', models.IntegerField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.categoria')),
                ('id_tipo_torneo', models.ForeignKey(blank=True, db_column='id_tipo_torneo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tipotorneo')),
            ],
            options={
                'db_table': 'torneos',
            },
        ),
        migrations.CreateModel(
            name='TemporadaXTorneoXEquipoXJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, to='myapp.equipo')),
                ('id_jugador', models.ForeignKey(db_column='id_jugador', on_delete=django.db.models.deletion.CASCADE, to='myapp.jugador')),
                ('id_temporada', models.ForeignKey(db_column='id_temporada', on_delete=django.db.models.deletion.CASCADE, to='myapp.temporada')),
                ('id_torneo', models.ForeignKey(db_column='id_torneo', on_delete=django.db.models.deletion.CASCADE, to='myapp.torneo')),
            ],
            options={
                'db_table': 'temporadas_x_torneos_x_equipos_x_jugadores',
            },
        ),
        migrations.AddField(
            model_name='temporada',
            name='id_torneo',
            field=models.ForeignKey(blank=True, db_column='id_torneo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.torneo'),
        ),
        migrations.CreateModel(
            name='PremioJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jugador', models.ForeignKey(blank=True, db_column='id_jugador', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.jugador')),
                ('id_premio_individual', models.ForeignKey(blank=True, db_column='id_premio_individual', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.premiosindividual')),
                ('id_temporada', models.ForeignKey(blank=True, db_column='id_temporada', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.temporada')),
                ('id_torneo', models.ForeignKey(blank=True, db_column='id_torneo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.torneo')),
            ],
            options={
                'db_table': 'premios_jugadores',
            },
        ),
        migrations.CreateModel(
            name='PremioEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipo', models.ForeignKey(blank=True, db_column='id_equipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.equipo')),
                ('id_premio_grupal', models.ForeignKey(blank=True, db_column='id_premio_grupal', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.premiosgrupal')),
                ('id_temporada', models.ForeignKey(blank=True, db_column='id_temporada', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.temporada')),
                ('id_torneo', models.ForeignKey(blank=True, db_column='id_torneo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.torneo')),
            ],
            options={
                'db_table': 'premios_equipos',
            },
        ),
        migrations.AddField(
            model_name='partido',
            name='id_torneo',
            field=models.ForeignKey(blank=True, db_column='id_torneo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.torneo'),
        ),
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transferencia', models.DateField(blank=True, null=True)),
                ('id_equipo_actual', models.ForeignKey(blank=True, db_column='id_equipo_actual', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.equipo')),
                ('id_equipo_nuevo', models.ForeignKey(blank=True, db_column='id_equipo_nuevo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_id_equipo_nuevo_set', to='myapp.equipo')),
                ('id_jugador', models.ForeignKey(blank=True, db_column='id_jugador', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.jugador')),
                ('id_torneo', models.ForeignKey(blank=True, db_column='id_torneo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.torneo')),
            ],
            options={
                'db_table': 'traspasos',
            },
        ),
    ]
