# Generated by Django 5.0.6 on 2024-11-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='figura',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='planilla',
            name='tarjeta_amarilla',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='planilla',
            name='tarjeta_roja',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
