# Generated by Django 5.0.6 on 2024-10-15 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_categoria_entrenador_equipo_equipoxentrenador_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporadaxtorneoxequipoxjugador',
            name='id_jugador',
            field=models.ForeignKey(blank=True, db_column='id_jugador', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.jugador'),
        ),
    ]
