# Generated by Django 5.0.6 on 2024-11-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_planilla_figura_planilla_tarjeta_amarilla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='figura',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='tarjeta_amarilla',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='tarjeta_roja',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
