# Generated by Django 5.1.1 on 2024-10-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('mostrar', models.BooleanField(default=False)),
                ('mostrado', models.BooleanField(default=False)),
            ],
        ),
    ]
