# Generated by Django 5.1.1 on 2024-10-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_aviso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='mostrado',
        ),
    ]
