# Generated by Django 5.0.6 on 2024-11-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_planilla_figura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='figura',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='participo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='tarjeta_amarilla',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='tarjeta_roja',
            field=models.BooleanField(default=False),
        ),
    ]
