# Generated by Django 5.1.1 on 2024-11-08 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_aviso_mostrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='activo_jugador',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='TemporadaXTorneoXGrupoXEquipoXJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, to='myapp.equipo')),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.grupo')),
                ('id_jugador', models.ForeignKey(blank=True, db_column='id_jugador', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.jugador')),
                ('id_temporada', models.ForeignKey(db_column='id_temporada', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.temporada')),
                ('id_torneo', models.ForeignKey(db_column='id_torneo', on_delete=django.db.models.deletion.CASCADE, to='myapp.torneo')),
            ],
            options={
                'db_table': 'temporadas_x_torneos_x_grupos_x_equipos_x_jugadores',
            },
        ),
        migrations.DeleteModel(
            name='TemporadaXTorneoXEquipoXJugador',
        ),
    ]
