# Generated by Django 5.0.6 on 2024-10-28 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_grupo_id_temporada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporadaxtorneoxgrupoxequipoxjugador',
            name='id_grupo',
            field=models.ForeignKey(db_column='id_grupo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.grupo'),
        ),
    ]
