# Generated by Django 5.0.6 on 2024-11-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_planilla_figura_alter_planilla_participo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='goles',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planilla',
            name='num_camiseta',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
