# Generated by Django 5.0.6 on 2024-11-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_planilla_goles_alter_planilla_num_camiseta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='penales',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='penales_equipo_1',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='penales_equipo_2',
        ),
    ]
