# Generated by Django 5.0.6 on 2024-11-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_resultado_penales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reglamento', models.CharField(max_length=100, unique=True)),
                ('archivo_reglamento', models.FileField(upload_to='reglamentos/')),
            ],
            options={
                'db_table': 'reglamentos',
            },
        ),
    ]
