# Generated by Django 5.0.6 on 2024-11-27 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_reglamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='id_equipo',
            field=models.ForeignKey(blank=True, db_column='id_equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.equipo'),
        ),
    ]
